// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package access_mocks

import (
	"context"

	"gitdev.devops.krungthai.com/starwolf/backend/common/app"
	"gitdev.devops.krungthai.com/starwolf/backend/common/httpclient"
	"github.com/11SF/dogjohn-be/app/identityflow/access"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthClientMock creates a new instance of AuthClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthClientMock {
	mock := &AuthClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthClientMock is an autogenerated mock type for the AuthClient type
type AuthClientMock struct {
	mock.Mock
}

type AuthClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthClientMock) EXPECT() *AuthClientMock_Expecter {
	return &AuthClientMock_Expecter{mock: &_m.Mock}
}

// IssueToken provides a mock function for the type AuthClientMock
func (_mock *AuthClientMock) IssueToken(ctx context.Context, req access.IssueTokenRequest) (httpclient.Response[app.Response[access.IssueTokenResponse]], error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for IssueToken")
	}

	var r0 httpclient.Response[app.Response[access.IssueTokenResponse]]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.IssueTokenRequest) (httpclient.Response[app.Response[access.IssueTokenResponse]], error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.IssueTokenRequest) httpclient.Response[app.Response[access.IssueTokenResponse]]); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(httpclient.Response[app.Response[access.IssueTokenResponse]])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.IssueTokenRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthClientMock_IssueToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueToken'
type AuthClientMock_IssueToken_Call struct {
	*mock.Call
}

// IssueToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req access.IssueTokenRequest
func (_e *AuthClientMock_Expecter) IssueToken(ctx interface{}, req interface{}) *AuthClientMock_IssueToken_Call {
	return &AuthClientMock_IssueToken_Call{Call: _e.mock.On("IssueToken", ctx, req)}
}

func (_c *AuthClientMock_IssueToken_Call) Run(run func(ctx context.Context, req access.IssueTokenRequest)) *AuthClientMock_IssueToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.IssueTokenRequest
		if args[1] != nil {
			arg1 = args[1].(access.IssueTokenRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthClientMock_IssueToken_Call) Return(response httpclient.Response[app.Response[access.IssueTokenResponse]], err error) *AuthClientMock_IssueToken_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *AuthClientMock_IssueToken_Call) RunAndReturn(run func(ctx context.Context, req access.IssueTokenRequest) (httpclient.Response[app.Response[access.IssueTokenResponse]], error)) *AuthClientMock_IssueToken_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveIdentity provides a mock function for the type AuthClientMock
func (_mock *AuthClientMock) ResolveIdentity(ctx context.Context, req access.ResolveIdentityRequest) (httpclient.Response[app.Response[access.ResolveIdentityResponse]], error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ResolveIdentity")
	}

	var r0 httpclient.Response[app.Response[access.ResolveIdentityResponse]]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.ResolveIdentityRequest) (httpclient.Response[app.Response[access.ResolveIdentityResponse]], error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.ResolveIdentityRequest) httpclient.Response[app.Response[access.ResolveIdentityResponse]]); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(httpclient.Response[app.Response[access.ResolveIdentityResponse]])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.ResolveIdentityRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthClientMock_ResolveIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveIdentity'
type AuthClientMock_ResolveIdentity_Call struct {
	*mock.Call
}

// ResolveIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - req access.ResolveIdentityRequest
func (_e *AuthClientMock_Expecter) ResolveIdentity(ctx interface{}, req interface{}) *AuthClientMock_ResolveIdentity_Call {
	return &AuthClientMock_ResolveIdentity_Call{Call: _e.mock.On("ResolveIdentity", ctx, req)}
}

func (_c *AuthClientMock_ResolveIdentity_Call) Run(run func(ctx context.Context, req access.ResolveIdentityRequest)) *AuthClientMock_ResolveIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.ResolveIdentityRequest
		if args[1] != nil {
			arg1 = args[1].(access.ResolveIdentityRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthClientMock_ResolveIdentity_Call) Return(response httpclient.Response[app.Response[access.ResolveIdentityResponse]], err error) *AuthClientMock_ResolveIdentity_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *AuthClientMock_ResolveIdentity_Call) RunAndReturn(run func(ctx context.Context, req access.ResolveIdentityRequest) (httpclient.Response[app.Response[access.ResolveIdentityResponse]], error)) *AuthClientMock_ResolveIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// NewMemberClientMock creates a new instance of MemberClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberClientMock {
	mock := &MemberClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MemberClientMock is an autogenerated mock type for the MemberClient type
type MemberClientMock struct {
	mock.Mock
}

type MemberClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MemberClientMock) EXPECT() *MemberClientMock_Expecter {
	return &MemberClientMock_Expecter{mock: &_m.Mock}
}

// GetMe provides a mock function for the type MemberClientMock
func (_mock *MemberClientMock) GetMe(ctx context.Context, req access.GetMemberMeRequest) (httpclient.Response[app.Response[access.GetMemberMeResponse]], error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 httpclient.Response[app.Response[access.GetMemberMeResponse]]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.GetMemberMeRequest) (httpclient.Response[app.Response[access.GetMemberMeResponse]], error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.GetMemberMeRequest) httpclient.Response[app.Response[access.GetMemberMeResponse]]); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(httpclient.Response[app.Response[access.GetMemberMeResponse]])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.GetMemberMeRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MemberClientMock_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type MemberClientMock_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
//   - req access.GetMemberMeRequest
func (_e *MemberClientMock_Expecter) GetMe(ctx interface{}, req interface{}) *MemberClientMock_GetMe_Call {
	return &MemberClientMock_GetMe_Call{Call: _e.mock.On("GetMe", ctx, req)}
}

func (_c *MemberClientMock_GetMe_Call) Run(run func(ctx context.Context, req access.GetMemberMeRequest)) *MemberClientMock_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.GetMemberMeRequest
		if args[1] != nil {
			arg1 = args[1].(access.GetMemberMeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MemberClientMock_GetMe_Call) Return(response httpclient.Response[app.Response[access.GetMemberMeResponse]], err error) *MemberClientMock_GetMe_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MemberClientMock_GetMe_Call) RunAndReturn(run func(ctx context.Context, req access.GetMemberMeRequest) (httpclient.Response[app.Response[access.GetMemberMeResponse]], error)) *MemberClientMock_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterMember provides a mock function for the type MemberClientMock
func (_mock *MemberClientMock) RegisterMember(ctx context.Context, req access.RegisterMemberRequest) (httpclient.Response[app.Response[access.RegisterMemberResponse]], error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterMember")
	}

	var r0 httpclient.Response[app.Response[access.RegisterMemberResponse]]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.RegisterMemberRequest) (httpclient.Response[app.Response[access.RegisterMemberResponse]], error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.RegisterMemberRequest) httpclient.Response[app.Response[access.RegisterMemberResponse]]); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(httpclient.Response[app.Response[access.RegisterMemberResponse]])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.RegisterMemberRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MemberClientMock_RegisterMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterMember'
type MemberClientMock_RegisterMember_Call struct {
	*mock.Call
}

// RegisterMember is a helper method to define mock.On call
//   - ctx context.Context
//   - req access.RegisterMemberRequest
func (_e *MemberClientMock_Expecter) RegisterMember(ctx interface{}, req interface{}) *MemberClientMock_RegisterMember_Call {
	return &MemberClientMock_RegisterMember_Call{Call: _e.mock.On("RegisterMember", ctx, req)}
}

func (_c *MemberClientMock_RegisterMember_Call) Run(run func(ctx context.Context, req access.RegisterMemberRequest)) *MemberClientMock_RegisterMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.RegisterMemberRequest
		if args[1] != nil {
			arg1 = args[1].(access.RegisterMemberRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MemberClientMock_RegisterMember_Call) Return(response httpclient.Response[app.Response[access.RegisterMemberResponse]], err error) *MemberClientMock_RegisterMember_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MemberClientMock_RegisterMember_Call) RunAndReturn(run func(ctx context.Context, req access.RegisterMemberRequest) (httpclient.Response[app.Response[access.RegisterMemberResponse]], error)) *MemberClientMock_RegisterMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrganizationClientMock creates a new instance of OrganizationClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationClientMock {
	mock := &OrganizationClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrganizationClientMock is an autogenerated mock type for the OrganizationClient type
type OrganizationClientMock struct {
	mock.Mock
}

type OrganizationClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OrganizationClientMock) EXPECT() *OrganizationClientMock_Expecter {
	return &OrganizationClientMock_Expecter{mock: &_m.Mock}
}

// GetCurrent provides a mock function for the type OrganizationClientMock
func (_mock *OrganizationClientMock) GetCurrent(ctx context.Context, req access.GetCurrentOrganizationRequest) (httpclient.Response[app.Response[access.GetCurrentOrganizationResponse]], error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrent")
	}

	var r0 httpclient.Response[app.Response[access.GetCurrentOrganizationResponse]]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.GetCurrentOrganizationRequest) (httpclient.Response[app.Response[access.GetCurrentOrganizationResponse]], error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.GetCurrentOrganizationRequest) httpclient.Response[app.Response[access.GetCurrentOrganizationResponse]]); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(httpclient.Response[app.Response[access.GetCurrentOrganizationResponse]])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.GetCurrentOrganizationRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrganizationClientMock_GetCurrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrent'
type OrganizationClientMock_GetCurrent_Call struct {
	*mock.Call
}

// GetCurrent is a helper method to define mock.On call
//   - ctx context.Context
//   - req access.GetCurrentOrganizationRequest
func (_e *OrganizationClientMock_Expecter) GetCurrent(ctx interface{}, req interface{}) *OrganizationClientMock_GetCurrent_Call {
	return &OrganizationClientMock_GetCurrent_Call{Call: _e.mock.On("GetCurrent", ctx, req)}
}

func (_c *OrganizationClientMock_GetCurrent_Call) Run(run func(ctx context.Context, req access.GetCurrentOrganizationRequest)) *OrganizationClientMock_GetCurrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.GetCurrentOrganizationRequest
		if args[1] != nil {
			arg1 = args[1].(access.GetCurrentOrganizationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrganizationClientMock_GetCurrent_Call) Return(response httpclient.Response[app.Response[access.GetCurrentOrganizationResponse]], err error) *OrganizationClientMock_GetCurrent_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *OrganizationClientMock_GetCurrent_Call) RunAndReturn(run func(ctx context.Context, req access.GetCurrentOrganizationRequest) (httpclient.Response[app.Response[access.GetCurrentOrganizationResponse]], error)) *OrganizationClientMock_GetCurrent_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterOrganization provides a mock function for the type OrganizationClientMock
func (_mock *OrganizationClientMock) RegisterOrganization(ctx context.Context, req access.RegisterOrganizationRequest) (httpclient.Response[app.Response[access.RegisterOrganizationResponse]], error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterOrganization")
	}

	var r0 httpclient.Response[app.Response[access.RegisterOrganizationResponse]]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.RegisterOrganizationRequest) (httpclient.Response[app.Response[access.RegisterOrganizationResponse]], error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.RegisterOrganizationRequest) httpclient.Response[app.Response[access.RegisterOrganizationResponse]]); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(httpclient.Response[app.Response[access.RegisterOrganizationResponse]])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.RegisterOrganizationRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrganizationClientMock_RegisterOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterOrganization'
type OrganizationClientMock_RegisterOrganization_Call struct {
	*mock.Call
}

// RegisterOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - req access.RegisterOrganizationRequest
func (_e *OrganizationClientMock_Expecter) RegisterOrganization(ctx interface{}, req interface{}) *OrganizationClientMock_RegisterOrganization_Call {
	return &OrganizationClientMock_RegisterOrganization_Call{Call: _e.mock.On("RegisterOrganization", ctx, req)}
}

func (_c *OrganizationClientMock_RegisterOrganization_Call) Run(run func(ctx context.Context, req access.RegisterOrganizationRequest)) *OrganizationClientMock_RegisterOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.RegisterOrganizationRequest
		if args[1] != nil {
			arg1 = args[1].(access.RegisterOrganizationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrganizationClientMock_RegisterOrganization_Call) Return(response httpclient.Response[app.Response[access.RegisterOrganizationResponse]], err error) *OrganizationClientMock_RegisterOrganization_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *OrganizationClientMock_RegisterOrganization_Call) RunAndReturn(run func(ctx context.Context, req access.RegisterOrganizationRequest) (httpclient.Response[app.Response[access.RegisterOrganizationResponse]], error)) *OrganizationClientMock_RegisterOrganization_Call {
	_c.Call.Return(run)
	return _c
}
