// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package access_mocks

import (
	"context"

	"github.com/11SF/dogjohn-be/app/order/access"
	mock "github.com/stretchr/testify/mock"
)

// NewHomeAssistantClientMock creates a new instance of HomeAssistantClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHomeAssistantClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HomeAssistantClientMock {
	mock := &HomeAssistantClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HomeAssistantClientMock is an autogenerated mock type for the HomeAssistantClient type
type HomeAssistantClientMock struct {
	mock.Mock
}

type HomeAssistantClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HomeAssistantClientMock) EXPECT() *HomeAssistantClientMock_Expecter {
	return &HomeAssistantClientMock_Expecter{mock: &_m.Mock}
}

// TriggerFeeder provides a mock function for the type HomeAssistantClientMock
func (_mock *HomeAssistantClientMock) TriggerFeeder(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TriggerFeeder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// HomeAssistantClientMock_TriggerFeeder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TriggerFeeder'
type HomeAssistantClientMock_TriggerFeeder_Call struct {
	*mock.Call
}

// TriggerFeeder is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HomeAssistantClientMock_Expecter) TriggerFeeder(ctx interface{}) *HomeAssistantClientMock_TriggerFeeder_Call {
	return &HomeAssistantClientMock_TriggerFeeder_Call{Call: _e.mock.On("TriggerFeeder", ctx)}
}

func (_c *HomeAssistantClientMock_TriggerFeeder_Call) Run(run func(ctx context.Context)) *HomeAssistantClientMock_TriggerFeeder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HomeAssistantClientMock_TriggerFeeder_Call) Return(err error) *HomeAssistantClientMock_TriggerFeeder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *HomeAssistantClientMock_TriggerFeeder_Call) RunAndReturn(run func(ctx context.Context) error) *HomeAssistantClientMock_TriggerFeeder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepositoryMock creates a new instance of OrderRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepositoryMock {
	mock := &OrderRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderRepositoryMock is an autogenerated mock type for the OrderRepository type
type OrderRepositoryMock struct {
	mock.Mock
}

type OrderRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepositoryMock) EXPECT() *OrderRepositoryMock_Expecter {
	return &OrderRepositoryMock_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function for the type OrderRepositoryMock
func (_mock *OrderRepositoryMock) GetOrder(ctx context.Context, orderID string) (*access.GetOrderResponse, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *access.GetOrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*access.GetOrderResponse, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *access.GetOrderResponse); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*access.GetOrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepositoryMock_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderRepositoryMock_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *OrderRepositoryMock_Expecter) GetOrder(ctx interface{}, orderID interface{}) *OrderRepositoryMock_GetOrder_Call {
	return &OrderRepositoryMock_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderID)}
}

func (_c *OrderRepositoryMock_GetOrder_Call) Run(run func(ctx context.Context, orderID string)) *OrderRepositoryMock_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepositoryMock_GetOrder_Call) Return(getOrderResponse *access.GetOrderResponse, err error) *OrderRepositoryMock_GetOrder_Call {
	_c.Call.Return(getOrderResponse, err)
	return _c
}

func (_c *OrderRepositoryMock_GetOrder_Call) RunAndReturn(run func(ctx context.Context, orderID string) (*access.GetOrderResponse, error)) *OrderRepositoryMock_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderHistory provides a mock function for the type OrderRepositoryMock
func (_mock *OrderRepositoryMock) GetOrderHistory(ctx context.Context, req access.OrderHistoryRequest) (*access.OrderHistoryResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderHistory")
	}

	var r0 *access.OrderHistoryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.OrderHistoryRequest) (*access.OrderHistoryResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.OrderHistoryRequest) *access.OrderHistoryResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*access.OrderHistoryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.OrderHistoryRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepositoryMock_GetOrderHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderHistory'
type OrderRepositoryMock_GetOrderHistory_Call struct {
	*mock.Call
}

// GetOrderHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - req access.OrderHistoryRequest
func (_e *OrderRepositoryMock_Expecter) GetOrderHistory(ctx interface{}, req interface{}) *OrderRepositoryMock_GetOrderHistory_Call {
	return &OrderRepositoryMock_GetOrderHistory_Call{Call: _e.mock.On("GetOrderHistory", ctx, req)}
}

func (_c *OrderRepositoryMock_GetOrderHistory_Call) Run(run func(ctx context.Context, req access.OrderHistoryRequest)) *OrderRepositoryMock_GetOrderHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.OrderHistoryRequest
		if args[1] != nil {
			arg1 = args[1].(access.OrderHistoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepositoryMock_GetOrderHistory_Call) Return(orderHistoryResponse *access.OrderHistoryResponse, err error) *OrderRepositoryMock_GetOrderHistory_Call {
	_c.Call.Return(orderHistoryResponse, err)
	return _c
}

func (_c *OrderRepositoryMock_GetOrderHistory_Call) RunAndReturn(run func(ctx context.Context, req access.OrderHistoryRequest) (*access.OrderHistoryResponse, error)) *OrderRepositoryMock_GetOrderHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderSummary provides a mock function for the type OrderRepositoryMock
func (_mock *OrderRepositoryMock) GetOrderSummary(ctx context.Context) (*access.OrderSummaryResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderSummary")
	}

	var r0 *access.OrderSummaryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*access.OrderSummaryResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *access.OrderSummaryResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*access.OrderSummaryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepositoryMock_GetOrderSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderSummary'
type OrderRepositoryMock_GetOrderSummary_Call struct {
	*mock.Call
}

// GetOrderSummary is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OrderRepositoryMock_Expecter) GetOrderSummary(ctx interface{}) *OrderRepositoryMock_GetOrderSummary_Call {
	return &OrderRepositoryMock_GetOrderSummary_Call{Call: _e.mock.On("GetOrderSummary", ctx)}
}

func (_c *OrderRepositoryMock_GetOrderSummary_Call) Run(run func(ctx context.Context)) *OrderRepositoryMock_GetOrderSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OrderRepositoryMock_GetOrderSummary_Call) Return(orderSummaryResponse *access.OrderSummaryResponse, err error) *OrderRepositoryMock_GetOrderSummary_Call {
	_c.Call.Return(orderSummaryResponse, err)
	return _c
}

func (_c *OrderRepositoryMock_GetOrderSummary_Call) RunAndReturn(run func(ctx context.Context) (*access.OrderSummaryResponse, error)) *OrderRepositoryMock_GetOrderSummary_Call {
	_c.Call.Return(run)
	return _c
}

// IsPaymentTxnRefDuplicate provides a mock function for the type OrderRepositoryMock
func (_mock *OrderRepositoryMock) IsPaymentTxnRefDuplicate(ctx context.Context, txnRef string) (bool, error) {
	ret := _mock.Called(ctx, txnRef)

	if len(ret) == 0 {
		panic("no return value specified for IsPaymentTxnRefDuplicate")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, txnRef)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, txnRef)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, txnRef)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepositoryMock_IsPaymentTxnRefDuplicate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPaymentTxnRefDuplicate'
type OrderRepositoryMock_IsPaymentTxnRefDuplicate_Call struct {
	*mock.Call
}

// IsPaymentTxnRefDuplicate is a helper method to define mock.On call
//   - ctx context.Context
//   - txnRef string
func (_e *OrderRepositoryMock_Expecter) IsPaymentTxnRefDuplicate(ctx interface{}, txnRef interface{}) *OrderRepositoryMock_IsPaymentTxnRefDuplicate_Call {
	return &OrderRepositoryMock_IsPaymentTxnRefDuplicate_Call{Call: _e.mock.On("IsPaymentTxnRefDuplicate", ctx, txnRef)}
}

func (_c *OrderRepositoryMock_IsPaymentTxnRefDuplicate_Call) Run(run func(ctx context.Context, txnRef string)) *OrderRepositoryMock_IsPaymentTxnRefDuplicate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepositoryMock_IsPaymentTxnRefDuplicate_Call) Return(b bool, err error) *OrderRepositoryMock_IsPaymentTxnRefDuplicate_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *OrderRepositoryMock_IsPaymentTxnRefDuplicate_Call) RunAndReturn(run func(ctx context.Context, txnRef string) (bool, error)) *OrderRepositoryMock_IsPaymentTxnRefDuplicate_Call {
	_c.Call.Return(run)
	return _c
}

// SavePaymentTxnLog provides a mock function for the type OrderRepositoryMock
func (_mock *OrderRepositoryMock) SavePaymentTxnLog(ctx context.Context, orderID string, response any) error {
	ret := _mock.Called(ctx, orderID, response)

	if len(ret) == 0 {
		panic("no return value specified for SavePaymentTxnLog")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, orderID, response)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepositoryMock_SavePaymentTxnLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SavePaymentTxnLog'
type OrderRepositoryMock_SavePaymentTxnLog_Call struct {
	*mock.Call
}

// SavePaymentTxnLog is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - response any
func (_e *OrderRepositoryMock_Expecter) SavePaymentTxnLog(ctx interface{}, orderID interface{}, response interface{}) *OrderRepositoryMock_SavePaymentTxnLog_Call {
	return &OrderRepositoryMock_SavePaymentTxnLog_Call{Call: _e.mock.On("SavePaymentTxnLog", ctx, orderID, response)}
}

func (_c *OrderRepositoryMock_SavePaymentTxnLog_Call) Run(run func(ctx context.Context, orderID string, response any)) *OrderRepositoryMock_SavePaymentTxnLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderRepositoryMock_SavePaymentTxnLog_Call) Return(err error) *OrderRepositoryMock_SavePaymentTxnLog_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepositoryMock_SavePaymentTxnLog_Call) RunAndReturn(run func(ctx context.Context, orderID string, response any) error) *OrderRepositoryMock_SavePaymentTxnLog_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitOrder provides a mock function for the type OrderRepositoryMock
func (_mock *OrderRepositoryMock) SubmitOrder(ctx context.Context, req access.SubmitOrderRequest) (*access.SubmitOrderResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SubmitOrder")
	}

	var r0 *access.SubmitOrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.SubmitOrderRequest) (*access.SubmitOrderResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.SubmitOrderRequest) *access.SubmitOrderResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*access.SubmitOrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.SubmitOrderRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepositoryMock_SubmitOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitOrder'
type OrderRepositoryMock_SubmitOrder_Call struct {
	*mock.Call
}

// SubmitOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req access.SubmitOrderRequest
func (_e *OrderRepositoryMock_Expecter) SubmitOrder(ctx interface{}, req interface{}) *OrderRepositoryMock_SubmitOrder_Call {
	return &OrderRepositoryMock_SubmitOrder_Call{Call: _e.mock.On("SubmitOrder", ctx, req)}
}

func (_c *OrderRepositoryMock_SubmitOrder_Call) Run(run func(ctx context.Context, req access.SubmitOrderRequest)) *OrderRepositoryMock_SubmitOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.SubmitOrderRequest
		if args[1] != nil {
			arg1 = args[1].(access.SubmitOrderRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepositoryMock_SubmitOrder_Call) Return(submitOrderResponse *access.SubmitOrderResponse, err error) *OrderRepositoryMock_SubmitOrder_Call {
	_c.Call.Return(submitOrderResponse, err)
	return _c
}

func (_c *OrderRepositoryMock_SubmitOrder_Call) RunAndReturn(run func(ctx context.Context, req access.SubmitOrderRequest) (*access.SubmitOrderResponse, error)) *OrderRepositoryMock_SubmitOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderFailed provides a mock function for the type OrderRepositoryMock
func (_mock *OrderRepositoryMock) UpdateOrderFailed(ctx context.Context, orderID string, reason string) error {
	ret := _mock.Called(ctx, orderID, reason)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, orderID, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepositoryMock_UpdateOrderFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderFailed'
type OrderRepositoryMock_UpdateOrderFailed_Call struct {
	*mock.Call
}

// UpdateOrderFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - reason string
func (_e *OrderRepositoryMock_Expecter) UpdateOrderFailed(ctx interface{}, orderID interface{}, reason interface{}) *OrderRepositoryMock_UpdateOrderFailed_Call {
	return &OrderRepositoryMock_UpdateOrderFailed_Call{Call: _e.mock.On("UpdateOrderFailed", ctx, orderID, reason)}
}

func (_c *OrderRepositoryMock_UpdateOrderFailed_Call) Run(run func(ctx context.Context, orderID string, reason string)) *OrderRepositoryMock_UpdateOrderFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderRepositoryMock_UpdateOrderFailed_Call) Return(err error) *OrderRepositoryMock_UpdateOrderFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepositoryMock_UpdateOrderFailed_Call) RunAndReturn(run func(ctx context.Context, orderID string, reason string) error) *OrderRepositoryMock_UpdateOrderFailed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderProcessing provides a mock function for the type OrderRepositoryMock
func (_mock *OrderRepositoryMock) UpdateOrderProcessing(ctx context.Context, orderID string, paymentTxnRef string) error {
	ret := _mock.Called(ctx, orderID, paymentTxnRef)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderProcessing")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, orderID, paymentTxnRef)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepositoryMock_UpdateOrderProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderProcessing'
type OrderRepositoryMock_UpdateOrderProcessing_Call struct {
	*mock.Call
}

// UpdateOrderProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - paymentTxnRef string
func (_e *OrderRepositoryMock_Expecter) UpdateOrderProcessing(ctx interface{}, orderID interface{}, paymentTxnRef interface{}) *OrderRepositoryMock_UpdateOrderProcessing_Call {
	return &OrderRepositoryMock_UpdateOrderProcessing_Call{Call: _e.mock.On("UpdateOrderProcessing", ctx, orderID, paymentTxnRef)}
}

func (_c *OrderRepositoryMock_UpdateOrderProcessing_Call) Run(run func(ctx context.Context, orderID string, paymentTxnRef string)) *OrderRepositoryMock_UpdateOrderProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderRepositoryMock_UpdateOrderProcessing_Call) Return(err error) *OrderRepositoryMock_UpdateOrderProcessing_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepositoryMock_UpdateOrderProcessing_Call) RunAndReturn(run func(ctx context.Context, orderID string, paymentTxnRef string) error) *OrderRepositoryMock_UpdateOrderProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// NewSlipOKClientMock creates a new instance of SlipOKClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSlipOKClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SlipOKClientMock {
	mock := &SlipOKClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SlipOKClientMock is an autogenerated mock type for the SlipOKClient type
type SlipOKClientMock struct {
	mock.Mock
}

type SlipOKClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SlipOKClientMock) EXPECT() *SlipOKClientMock_Expecter {
	return &SlipOKClientMock_Expecter{mock: &_m.Mock}
}

// VerifySlip provides a mock function for the type SlipOKClientMock
func (_mock *SlipOKClientMock) VerifySlip(ctx context.Context, req access.VerifySlipRequest) (access.VerifySlipResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for VerifySlip")
	}

	var r0 access.VerifySlipResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.VerifySlipRequest) (access.VerifySlipResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.VerifySlipRequest) access.VerifySlipResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(access.VerifySlipResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.VerifySlipRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SlipOKClientMock_VerifySlip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifySlip'
type SlipOKClientMock_VerifySlip_Call struct {
	*mock.Call
}

// VerifySlip is a helper method to define mock.On call
//   - ctx context.Context
//   - req access.VerifySlipRequest
func (_e *SlipOKClientMock_Expecter) VerifySlip(ctx interface{}, req interface{}) *SlipOKClientMock_VerifySlip_Call {
	return &SlipOKClientMock_VerifySlip_Call{Call: _e.mock.On("VerifySlip", ctx, req)}
}

func (_c *SlipOKClientMock_VerifySlip_Call) Run(run func(ctx context.Context, req access.VerifySlipRequest)) *SlipOKClientMock_VerifySlip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.VerifySlipRequest
		if args[1] != nil {
			arg1 = args[1].(access.VerifySlipRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SlipOKClientMock_VerifySlip_Call) Return(response access.VerifySlipResponse, err error) *SlipOKClientMock_VerifySlip_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *SlipOKClientMock_VerifySlip_Call) RunAndReturn(run func(ctx context.Context, req access.VerifySlipRequest) (access.VerifySlipResponse, error)) *SlipOKClientMock_VerifySlip_Call {
	_c.Call.Return(run)
	return _c
}
