// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package access_mocks

import (
	"context"

	"github.com/11SF/dogjohn-be/app/feeder/access"
	mock "github.com/stretchr/testify/mock"
)

// NewFeederRepositoryMock creates a new instance of FeederRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFeederRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FeederRepositoryMock {
	mock := &FeederRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FeederRepositoryMock is an autogenerated mock type for the FeederRepository type
type FeederRepositoryMock struct {
	mock.Mock
}

type FeederRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FeederRepositoryMock) EXPECT() *FeederRepositoryMock_Expecter {
	return &FeederRepositoryMock_Expecter{mock: &_m.Mock}
}

// GetAvailability provides a mock function for the type FeederRepositoryMock
func (_mock *FeederRepositoryMock) GetAvailability(ctx context.Context) (*access.FeederAvailabilityResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailability")
	}

	var r0 *access.FeederAvailabilityResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*access.FeederAvailabilityResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *access.FeederAvailabilityResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*access.FeederAvailabilityResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FeederRepositoryMock_GetAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailability'
type FeederRepositoryMock_GetAvailability_Call struct {
	*mock.Call
}

// GetAvailability is a helper method to define mock.On call
//   - ctx context.Context
func (_e *FeederRepositoryMock_Expecter) GetAvailability(ctx interface{}) *FeederRepositoryMock_GetAvailability_Call {
	return &FeederRepositoryMock_GetAvailability_Call{Call: _e.mock.On("GetAvailability", ctx)}
}

func (_c *FeederRepositoryMock_GetAvailability_Call) Run(run func(ctx context.Context)) *FeederRepositoryMock_GetAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FeederRepositoryMock_GetAvailability_Call) Return(feederAvailabilityResponse *access.FeederAvailabilityResponse, err error) *FeederRepositoryMock_GetAvailability_Call {
	_c.Call.Return(feederAvailabilityResponse, err)
	return _c
}

func (_c *FeederRepositoryMock_GetAvailability_Call) RunAndReturn(run func(ctx context.Context) (*access.FeederAvailabilityResponse, error)) *FeederRepositoryMock_GetAvailability_Call {
	_c.Call.Return(run)
	return _c
}
