// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package access_mocks

import (
	"context"

	"github.com/11SF/dogjohn-be/app/payment/access"
	mock "github.com/stretchr/testify/mock"
)

// NewPaymentRepositoryMock creates a new instance of PaymentRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentRepositoryMock {
	mock := &PaymentRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PaymentRepositoryMock is an autogenerated mock type for the PaymentRepository type
type PaymentRepositoryMock struct {
	mock.Mock
}

type PaymentRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentRepositoryMock) EXPECT() *PaymentRepositoryMock_Expecter {
	return &PaymentRepositoryMock_Expecter{mock: &_m.Mock}
}

// GetDetails provides a mock function for the type PaymentRepositoryMock
func (_mock *PaymentRepositoryMock) GetDetails(ctx context.Context) (*access.PaymentDetailsResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDetails")
	}

	var r0 *access.PaymentDetailsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*access.PaymentDetailsResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *access.PaymentDetailsResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*access.PaymentDetailsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentRepositoryMock_GetDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetails'
type PaymentRepositoryMock_GetDetails_Call struct {
	*mock.Call
}

// GetDetails is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PaymentRepositoryMock_Expecter) GetDetails(ctx interface{}) *PaymentRepositoryMock_GetDetails_Call {
	return &PaymentRepositoryMock_GetDetails_Call{Call: _e.mock.On("GetDetails", ctx)}
}

func (_c *PaymentRepositoryMock_GetDetails_Call) Run(run func(ctx context.Context)) *PaymentRepositoryMock_GetDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PaymentRepositoryMock_GetDetails_Call) Return(paymentDetailsResponse *access.PaymentDetailsResponse, err error) *PaymentRepositoryMock_GetDetails_Call {
	_c.Call.Return(paymentDetailsResponse, err)
	return _c
}

func (_c *PaymentRepositoryMock_GetDetails_Call) RunAndReturn(run func(ctx context.Context) (*access.PaymentDetailsResponse, error)) *PaymentRepositoryMock_GetDetails_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrice provides a mock function for the type PaymentRepositoryMock
func (_mock *PaymentRepositoryMock) GetPrice(ctx context.Context, priceID string) (*access.Price, error) {
	ret := _mock.Called(ctx, priceID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrice")
	}

	var r0 *access.Price
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*access.Price, error)); ok {
		return returnFunc(ctx, priceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *access.Price); ok {
		r0 = returnFunc(ctx, priceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*access.Price)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, priceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentRepositoryMock_GetPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrice'
type PaymentRepositoryMock_GetPrice_Call struct {
	*mock.Call
}

// GetPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - priceID string
func (_e *PaymentRepositoryMock_Expecter) GetPrice(ctx interface{}, priceID interface{}) *PaymentRepositoryMock_GetPrice_Call {
	return &PaymentRepositoryMock_GetPrice_Call{Call: _e.mock.On("GetPrice", ctx, priceID)}
}

func (_c *PaymentRepositoryMock_GetPrice_Call) Run(run func(ctx context.Context, priceID string)) *PaymentRepositoryMock_GetPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PaymentRepositoryMock_GetPrice_Call) Return(price *access.Price, err error) *PaymentRepositoryMock_GetPrice_Call {
	_c.Call.Return(price, err)
	return _c
}

func (_c *PaymentRepositoryMock_GetPrice_Call) RunAndReturn(run func(ctx context.Context, priceID string) (*access.Price, error)) *PaymentRepositoryMock_GetPrice_Call {
	_c.Call.Return(run)
	return _c
}
